# Generated by Django 5.0.6 on 2025-06-13 13:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyprofile',
            options={},
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='about',
            new_name='company_culture',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='logo',
            new_name='company_logo',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='website',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='linkedin_url',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='office_locations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='preferred_job_types',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='preferred_locations',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='preferred_salary',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='headline',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_size',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma separated list of skills'),
        ),
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_views', models.PositiveIntegerField(default=0)),
                ('last_login_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_applications', models.PositiveIntegerField(default=0)),
                ('total_job_posts', models.PositiveIntegerField(default=0)),
                ('application_success_rate', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
