# Generated by Django 5.0.6 on 2025-06-12 19:24

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewing', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interviewing', 'Interviewing'), ('offered', 'Offer Extended'), ('accepted', 'Offer Accepted'), ('rejected', 'Not Selected'), ('withdrawn', 'Application Withdrawn')], default='pending', max_length=20)),
                ('resume', models.FileField(help_text='PDF files only', upload_to='applications/resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('cover_letter', models.TextField(blank=True)),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('availability', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer_notes', models.TextField(blank=True)),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
