# Generated by Django 5.0.6 on 2025-06-13 13:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_private', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-applied_date']},
        ),
        migrations.RemoveIndex(
            model_name='jobapplication',
            name='application_status_feb364_idx',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='created_at',
            new_name='applied_date',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='employer_notes',
            new_name='general_notes',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='updated_at',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='interview_date',
            new_name='review_date',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='expected_salary',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(null=True, upload_to='applications/resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
        migrations.AddField(
            model_name='applicationnote',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='applications.jobapplication'),
        ),
        migrations.AddField(
            model_name='applicationnote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
