# Generated by Django 5.0.6 on 2025-06-12 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='users.companyprofile'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['created_at', 'deadline', 'is_active'], name='jobs_job_created_2181f4_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['location'], name='jobs_job_locatio_8b2f8c_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['employment_type'], name='jobs_job_employm_743f88_idx'),
        ),
    ]
